// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	userentity "immersive/domains/login/entities"

	mock "github.com/stretchr/testify/mock"
)

// LoginRepoMock is an autogenerated mock type for the ILoginRepo type
type LoginRepoMock struct {
	mock.Mock
}

// GetByEmail provides a mock function with given fields: mentor
func (_m *LoginRepoMock) GetByEmail(mentor userentity.MentorEntity) (userentity.MentorEntity, error) {
	ret := _m.Called(mentor)

	var r0 userentity.MentorEntity
	if rf, ok := ret.Get(0).(func(userentity.MentorEntity) userentity.MentorEntity); ok {
		r0 = rf(mentor)
	} else {
		r0 = ret.Get(0).(userentity.MentorEntity)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(userentity.MentorEntity) error); ok {
		r1 = rf(mentor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewLoginRepoMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewLoginRepoMock creates a new instance of LoginRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLoginRepoMock(t mockConstructorTestingTNewLoginRepoMock) *LoginRepoMock {
	mock := &LoginRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
